[project]
name = 'fpe'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.fpe]
path = 'contracts/fpe.clar'
clarity_version = 3
epoch = 3.1

[contracts.withdrawal-protection]
path = 'contracts/withdrawal-protection.clar'
clarity_version = 3
epoch = 3.1

[contracts.contract-templates]
path = 'contracts/contract-templates.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
